page my_bets and bet_form on lot page
htmlacademy-php/1630817-yeticave-12 pull request #16
Opened 2021-03-13 12:13 UTC by Mansik18

2021-03-13 12:15 UTC, Mansik18 commented
ой, я забыл отформатировать, можно в следующем задании сделаю?

2021-03-15 19:53 UTC, ademaro commented on add.php
>          'user_name' => isset($_SESSION['login']) ? $_SESSION['login'] : '',
https://up.htmlacademy.ru/php/12/criteries#d9 — частично можно тут отнести, вместо пустой строки можно было бы false. Не особо принципиально, конечно, но более чисто получилось бы...

2021-03-15 19:54 UTC, ademaro commented on functions.php
> + * Валидация email при входе на сайт
ну тут уже не email валидируем)

2021-03-15 19:59 UTC, ademaro commented on lot.php
>      $lot = get_lot_info($con, $_GET['lot_id']);
а почему get_lot_info() возвращает массив лотов? для чего ниже используешь первый элемент массива? почему бы сразу не выдавать то, что нужно?

2021-03-15 20:00 UTC, ademaro commented on lot.php
> +if (isset($_GET['lot_id']) ? is_numeric($_GET['lot_id']) : false) {
в условии ещё и тернарный оператор?

2021-03-15 20:00 UTC, ademaro commented on lot.php
> +if (isset($_GET['lot_id']) ? is_numeric($_GET['lot_id']) : false) {
думаю, нужно упростить

2021-03-15 20:03 UTC, ademaro commented on lot.php
> +        if ($is_auth && $_SERVER['REQUEST_METHOD'] == 'POST' && ! empty($_POST['cost'])) {
когда это будет выполняться? ты же выше УЖЕ зашёл в GET...

Смысл такой: проверяем POST это или GET изначально (на запись или на чтение), а от этого уже и развиваем... Ну и сравнение у нас строгое всегда должно быть, если что...

2021-03-15 20:06 UTC, ademaro commented on lot.php
> +            $insert_bet = ! array_filter($errors) ? insert_new_bet($con, $_POST['cost'], $_GET['lot_id'], $_SESSION['id']) : false;
вообще мешанина GET, POST на одной строке... ещё и тернарный оператор. Сам сможешь сразу сказать, что тут происходит? Или придётся думать?) Если придётся думать — скорее всего не очень решение)) Давай всё-таки упростим. Далее созвонимся — пройдёмся по коду вместе, посмотрим на сколько сам сможешь рассказать что происходит на некоторых строках))

2021-03-15 20:08 UTC, ademaro requested changes
Давай поработаем немного над кодом, что бы стало всё понятнее

2021-04-01 06:00 UTC, Mansik18 commented
Можно ли как-то убрать повторение кода на lot.php

2021-04-04 13:59 UTC, ademaro commented on functions.php
> +///**
если не нужен код — удаляем

2021-04-04 14:01 UTC, ademaro commented on config.php
> +//    ->setUsername('keks@phpdemo.ru')
в конфиге имеет смысл оставить константы для имени пользователя и пароля для отправки почты, а сам код — уже в контроллер отправки почтовых сообщений

2021-04-04 14:04 UTC, ademaro commented
по lot.php — достаточно всё локанично https://github.com/Mansik18/1630817-yeticave-12/blob/module8-task2/lot.php
Поясни подробнее, плиз, что именно имеешь в виду?

2021-04-04 14:50 UTC, merged